export interface UserInfo {
    uid: number,
    username: string,
    nickname: string,
    avatar: string,
    mail: string,
    phone: string,
    background: string,
    gender: number,
    description: string,
    exp: number,
    coin: number,
    vip: number,
    auth: number,
    auth_msg: string,
}